spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true